// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvZsri526fnG0kuW6KzEQmlsIS6DlncAk',
    appId: '1:1020872415882:web:8a74d1214ce6a640366b73',
    messagingSenderId: '1020872415882',
    projectId: 'calm-1232c',
    authDomain: 'calm-1232c.firebaseapp.com',
    storageBucket: 'calm-1232c.firebasestorage.app',
    measurementId: 'G-8E9X8Z5WH9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOtSTVMbaksPK3HkGveQ6eBfesQwXdjzk',
    appId: '1:1020872415882:android:36b323bb14219bc7366b73',
    messagingSenderId: '1020872415882',
    projectId: 'calm-1232c',
    storageBucket: 'calm-1232c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpUpWNNEfTCpduzrjS6ZKu7065MSMo6CU',
    appId: '1:1020872415882:ios:447813946a856c96366b73',
    messagingSenderId: '1020872415882',
    projectId: 'calm-1232c',
    storageBucket: 'calm-1232c.firebasestorage.app',
    iosBundleId: 'com.example.calm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpUpWNNEfTCpduzrjS6ZKu7065MSMo6CU',
    appId: '1:1020872415882:ios:447813946a856c96366b73',
    messagingSenderId: '1020872415882',
    projectId: 'calm-1232c',
    storageBucket: 'calm-1232c.firebasestorage.app',
    iosBundleId: 'com.example.calm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvZsri526fnG0kuW6KzEQmlsIS6DlncAk',
    appId: '1:1020872415882:web:f6a8c5479f27c224366b73',
    messagingSenderId: '1020872415882',
    projectId: 'calm-1232c',
    authDomain: 'calm-1232c.firebaseapp.com',
    storageBucket: 'calm-1232c.firebasestorage.app',
    measurementId: 'G-9H6LLPNM6E',
  );
}
